//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Puestos_de_Trabajo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuestoTrabajo
    {
        public int id { get; set; }
        public Nullable<int> id_Empresa { get; set; }
        public string id_Usuario { get; set; }
        public Nullable<int> id_Categoria { get; set; }
        public string url { get; set; }
        public string cargo { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha_Publicacion { get; set; }
        public string tipo { get; set; }
        public byte[] logo { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> publico { get; set; }
        public Nullable<int> dias_trabajo_linea { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Categoria Categoria { get; set; }
        public virtual Empresa Empresa { get; set; }
    }
}
