//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Puestos_de_Trabajo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo
    {
        public string Descripcion { get; set; }
    }
}
