//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Puestos_de_Trabajo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int id { get; set; }
        public Nullable<int> id_TipoUsuario { get; set; }
        public string nombre { get; set; }
        public string url { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    
        public virtual TipoUsuario TipoUsuario { get; set; }
    }
}
